---
- name: ASG Auto Configuration
  hosts: tag_name_dev          # <-- Use correct tag key (case sensitive)
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for SSH to be ready
      wait_for_connection:
        timeout: 300
        sleep: 10

    - name: Ensure python3 is installed
      raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          yum install -y python3
        fi
      changed_when: false

  tasks:
    - name: Create test file
      copy:
        content: "ANSIBLE_OK\n"
        dest: /tmp/ansible_test.txt
        mode: '0644'

# ec2-user]mkdir ansible and vi deploy.yaml
